server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: orders
          uri: http://orders-service:8080
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1

        - id: payments
          uri: http://payments-service:8080
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
